name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup conda environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml

      # Install MLflow
      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow==2.19.0

      # Run MLflow Project
      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run MLProject --experiment-name "CI Bank Marketing"

      # Upload MLflow artifacts
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

      # Login to Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image from MLflow model
      - name: Build Docker Image
        shell: bash -l {0}
        run: |
          MODEL_PATH=$(find mlruns -type d -name model | head -n 1)
          echo "Using model path: $MODEL_PATH"

          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n ${{ secrets.DOCKER_USERNAME }}/bank-marketing-mlflow

      # Push Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bank-marketing-mlflow
